version: '3.1' 
services: 
  db:
    image: mysql:8.0.21
    environment:
      - MYSQL_DATABASE=paul
      - MYSQL_ROOT_PASSWORD=secret
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080